version: "3.9"

services:
    app:
        build:
            context: .
            dockerfile: ./Dockerfile
        restart: unless-stopped
        tty: true
        environment:
            XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003 start_with_request=yes
            PHP_IDE_CONFIG: serverName=todo
            XDEBUG_MODE: debug
            XDEBUG_SESSION: PHPSTORM
        volumes:
            - ./app:/app
        depends_on:
            - buggregator
            - mysql
            - redis
            - rabbitmq
        ports:
            - 8080:8080
        networks:
            - todo

    buggregator:
        image: ghcr.io/buggregator/server:latest
        ports:
            - 8000:8000
            - 1025:1025
            - 9912:9912
            - 9913:9913
        networks:
            - todo

    mysql:
        image: mysql:8.0
        restart: unless-stopped
        environment:
            - MYSQL_DATABASE=todo
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=1
        ports:
            - "3377:3306"
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - todo

    redis:
        image: redis:6.0
        restart: unless-stopped
        ports:
            - "6377:6379"
        volumes:
            - redis-data:/data
        networks:
            - todo

    nodejs:
        image: node:21.6.2-alpine
#        tty: true
        working_dir: /app
        volumes:
            - ./:/app
        networks:
            - todo
        ports:
            - "3000:3000"

    rabbitmq:
        image: rabbitmq:3.8-management
        restart: unless-stopped
        ports:
            - "15677:15672"
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest
        networks:
            - todo

volumes:
    mysql-data: { }
    redis-data: { }

networks:
    todo: {}
